#+title: Logiciels & droit d'auteur
#+author: Etalab
#+date: Novembre 2019
#+options: num:t toc:2

* Droit d'auteur & logiciels : régime général

*Article L.111-1 CPI* : “L'auteur d'une oeuvre de l'esprit jouit sur
cette oeuvre, du seul fait de sa création, d'un droit de propriété
incorporelle exclusif et opposable à tous. Ce droit comporte des
attributs d'ordre intellectuel et moral ainsi que des attributs
d'ordre patrimonial, qui sont déterminés par les livres Ier et III du
présent code. L'existence ou la conclusion d'un contrat de louage
d'ouvrage ou de service par l'auteur d'une oeuvre de l'esprit
n'emporte pas dérogation à la jouissance du droit reconnu par le
premier alinéa, sous réserve des exceptions prévues par le présent
code. Sous les mêmes réserves, il n'est pas non plus dérogé à la
jouissance de ce même droit lorsque l'auteur de l'oeuvre de l'esprit
est un agent de l'Etat, d'une collectivité territoriale, d'un
établissement public à caractère administratif, d'une autorité
administrative indépendante dotée de la personnalité morale ou de la
Banque de France (...) ».

*Article L. 112-2, 13° CPI* : « Sont considérés notamment comme oeuvres
de l'esprit au sens du présent code : (...) les logiciels (...) ».

Les logiciels peuvent donc être protégés par des droit d'auteurs.

Eléments non protégeables :

- Exclusion de l'idée[fn:1]
- Exclusion de l'algorithme et du langage de programmation[fn:2]
- Exclusion des fonctionnalités (les objectifs que le logiciel vise à atteindre)[fn:3]

/NB : les programmes d'ordinateur sont exclus de toute brevabilité en
principe/[fn:4].

Eléments protégeables, selon deux sources juridiques :

- *droit commun* du droit d'auteur : documentation auxiliaire, les
  effets audiovisuels (forme exécutée du logiciel), les interfaces
  graphiques[fn:5] ;

- *droit spécial* du droit d'auteur applicable au logiciel : pour le
  code source (mais aussi le code objet, l'organigramme, etc) →
  directive n°91/250, remplacée par la *Directive 2009/24/CE* du
  Parlement européen et du Conseil du 23 avril 2009 concernant la
  protection juridique des programmes d'ordinateur.

** Qualification objective du caractère original de l'oeuvre

*Arrêt Pachot* (1986)[fn:6] : l'originalité du logiciel est caractérisée
si il est constaté un «  *effort personnalisé* allant au-delà de la
simple mise en œuvre d'une logique automatique et contraignante et que
la matérialisation de cet effort résidait dans une structure
individualisée », il faut donc un « apport intellectuel » de l'auteur.

** Détermination du titulaire des droits

Il faut une création de logiciel faite de manière indépendante pour
jouir de droits d'auteur : si la création a été réalisée par plusieurs
auteurs travaillant en commun, poursuivant un objectif partagé, elle
sera considérée comme une œuvre de collaboration et les droits sur
cette dernière seront indivis[fn:7].

Il est possible de procéder à une *cession du droit d'exploitation*, et
de la rémunération en découlant.

En principe, il faut une rémunération proportionnelle aux recettes
générées par la vente ou l'exploitation de l'œuvre. Mais en matière de
création logicielle, la rémunération forfaitaire est autorisée si elle
est juste[fn:8].

** Les logiciels produits dans le cadre d'un contrat de commande

En l'absence de dispositions spécifiques, la réalisation d'une œuvre,
de manière générale, dans le cadre d'un contrat de commande ne
transfère au commanditaire que la propriété matérielle sur cette
réalisation, et non un droit d'exploitation[fn:9].

Il est donc non seulement possible mais aussi nécessaire pour
l'administration de procéder à des contrats de cession de droit
d'auteur lorsqu'elle recourt aux services d'un tiers.

Cas de la création logicielle salariée : *Art. L. 113-9, al. 1er, CPI*
dispose que « sauf dispositions statutaires ou stipulations
contraires, les droits patrimoniaux sur les logiciels et leur
documentation créés par un ou plusieurs employés dans l'exercice de
leurs fonctions ou d'après les instructions de leur employeur sont
dévolus à l'employeur qui est seul habilité à les exercer ».

Ainsi, les droits de l'auteur salarié sont automatiquement transférés
à l'employeur, *y compris pour les agents publics*.

Attention : cette dévolution forcée ne concerne que les éléments du
logiciel qui sont soumis au droit spécial et ne vise que les droits
patrimoniaux.

L'auteur reste donc toujours investi d'un droit moral sur son
œuvre. Le droit moral dans le régime général confère à l'auteur le
respect de son nom, de sa qualité et de son œuvre. Il est constitué
des prérogatives suivantes : droit de divulgation, le droit de
paternité, le droit au respect de l'intégralité de son œuvre, le droit
de retrait ou de repentir. Lorsque l'auteur du logiciel est un salarié
ou un agent public, le droit moral couvre uniquement le droit de
divulgation et le droit de paternité.

Pour bénéficier de cette disposition spéciale, l'œuvre doit avoir été
créée par l'agent public dans l'exercice de ses fonctions, mais en
réalité l'appréciation par les juges est assez large[fn:10].

** Contenu des droits d'auteur : les droits patrimoniaux et les droit moraux

*** Les droits patrimoniaux

- *droit de reproduction* : L'auteur bénéficie d'un large pouvoir de
  contrôle sur la reproduction, qu'elle soit permanente ou provisoire ;

- *droit de distribution* : il s'épuise par le premier usage (sauf en
  matière de location), ainsi le titulaire de droits ne pourra plus,
  une fois autorisée la vente d'un exemplaire dans un État membre de
  l'UE, en contrôler la circulation dans les autres États membres.

*Article L122-6 CPI :*

« Sous réserve des dispositions de l'article L. 122-6-1, le droit
d'exploitation appartenant à l'auteur d'un logiciel comprend le droit
d'effectuer et d'autoriser :

1. La reproduction permanente ou provisoire d'un logiciel en tout ou
   partie par tout moyen et sous toute forme. Dans la mesure où le
   chargement, l'affichage, l'exécution, la transmission ou le
   stockage de ce logiciel nécessitent une reproduction, ces actes ne
   sont possibles qu'avec l'autorisation de l'auteur ;

2. La traduction, l'adaptation, l'arrangement ou toute autre
   modification d'un logiciel et la reproduction du logiciel en
   résultant;

3. La mise sur le marché à titre onéreux ou gratuit, y compris la
   location, du ou des exemplaires d'un logiciel par tout
   procédé. Toutefois, la première vente d'un exemplaire d'un logiciel
   dans le territoire d'un Etat membre de la Communauté européenne ou
   d'un Etat partie à l'accord sur l'Espace économique européen par
   l'auteur ou avec son consentement épuise le droit de mise sur le
   marché de cet exemplaire dans tous les Etats membres à l'exception
   du droit d'autoriser la location ultérieure d'un exemplaire. »

*** Les droits moraux

*Article L121-7-1 CPI :*

Le droit de divulgation reconnu à *l'agen*t mentionné au troisième
alinéa de l'article L. 111-1, qui a créé une oeuvre de l'esprit dans
l'exercice de ses fonctions ou d'après les instructions reçues,
s'exerce dans le respect des règles auxquelles il est soumis en sa
qualité d'agent et de celles qui régissent l'organisation, le
fonctionnement et l'activité de la personne publique qui
l'emploie. L'agent ne peut :

1. S'opposer à la modification de l'oeuvre décidée dans l'intérêt du
   service par l'autorité investie du pouvoir hiérarchique, lorsque
   cette modification ne porte pas atteinte à son honneur ou à sa
   réputation ;

2. Exercer son droit de repentir et de retrait, sauf accord de
   l'autorité investie du pouvoir hiérarchique.

Dans le cadre du régime spécial applicables aux logiciels, lorsqu'il
s'agit d'un agent visé à l'article L111-1 du CPI : les seuls droits
moraux de l'auteur maintenus sont :

- *le droit de divulgation* (qui permet à l'auteur de décider du moment
  où l'œuvre rencontrera le public) ;

- *le droit à la paternité* (droit d'apposition et d'opposition qui lui
  permet de faire apparaître ou de cacher son nom et sa qualité à
  l'occasion de chaque exploitation de l'œuvre).

*** Restrictions aux droits d'auteur sur le logiciel

Tout utilisateur légitime, malgré l'existence de droits d'auteurs, a
le droit :

- d'utiliser et de rectifier le logiciel[fn:11] ;

- d'effectuer une copie de sauvegarde si elle « est nécessaire pour
  préserver l'utilisation du logiciel »[fn:12] ;

- d'étudier, observer et tester le fonctionnement du logiciel[fn:13] ;

- de procéder à une décompilation : l'utilisateur peut récupérer le
  code afin de permettre que le logiciel soit inter-opérable avec
  d'autres[fn:14].

→ Pour ce qui est des délais de prescription : pour les droits
patrimoniaux, la durée est en principe de 70 ans /post mortem auctoris/
(le délai commence à courir à la mort du dernier des coauteurs). En
revanche, le droit moral est quant à lui perpétuel[fn:15].

Pour résumer, en matière de logiciel, le droit d'auteur est aménagé
via des règles particulières : dans le cadre de la protection d'un
logiciel : Droits d'auteurs permet de protéger les = droits
patrimoniaux (distribution et reproduction) + droits moraux (droit de
divulgation + droit de paternité).

Formalisme pour la cession des droits : il faut signer un contrat.

*Art. L. 131-3 CPI* : La transmission des droits d'auteur est
subordonnée à la condition que chacun des droits cédés fasse l'objet
d'une mention distincte dans l'acte de cession et que le domaine
d'exploitation des droits cédés soit délimité quant à son étendue et à
sa destination, quant au lieu et quant à la durée.

→ Si ces droits sont possédés par des tiers (externes à
l'administration) :

En cas de cession : on ne cède que les droits patrimoniaux, mais les
droits moraux subsistent (l'auteur n'as pas de droit de retrait ou de
repentir) : l'auteur ne peut s'opposer aux modifications du logiciel
que s'il prouve que cela porte atteinte à son honneur et à sa
réputation.

En l'absence de cession : la réutilisation ne sera possible qu'avec
l'autorisation expresse de l'auteur (mais la diffusion, elle, sera
libre dès lors que le droit de distribution aura été épuisé).

→ Si ces droits sont possédés par un agent public : si le logiciel a
été créé dans le cadre de l'exercice de ses fonctions (appréciation
très large) : les droits patrimoniaux sont automatiquement transférés
à l'administration.

*ATTENTION :*

- cela ne fonctionne que pour les agents de l'Etat, des collectivités
  publiques et des établissements publics à caractère administratif ;
- cela ne concerne que les éléments protégés par le droit spécial (= code source) ;
- cela ne concerne que les droits patrimoniaux (pas le droit moral) ;
- dans le cas contraire, l'agent public doit être considéré comme un tiers.

* Droits d'auteur : régime applicable aux agents publics

Deux situations sont à distinguer pour les logiciels :

Pour les oeuvres, de manière générale, produites par un agent public, le
régime applicable est issu de la loi du 1^{er} août 2006 → articles
L. 121-7-1, et L. 131-3-1 à L. 131-3-3 du CPI.

Pour les agents de l'Etat : ce sont les personnels civils et
militaires, fonctionnaires statutaires ou employés, placés /sous
contrat de travail avec l'Etat français/. Les agents des collectivités
locales ou des établissements publics ne sont pas, sauf exception (par
exemple mise à disposition), assimilés à des fonctionnaires d'Etat,
quand bien même ils relèveraient des statuts de la fonction
publique[fn:16].

*Art. L. 131-3-1 du CPI* : « Dans la mesure strictement nécessaire à
l'accomplissement d'une mission de service public, le droit
d'exploitation d'une oeuvre créée par un agent de l'Etat dans
l'exercice de ses fonctions ou d'après les instructions reçues est,
dès la création, cédée de plein droit à l'Etat.

Pour l'exploitation commerciale de l'oeuvre mentionnée au premier
alinéa, l'Etat ne dispose envers l'agent auteur que d'un droit de
préférence. Cette disposition n'est pas applicable dans le cas
d'activités de recherche scientifique d'un établissement public à
caractère scientifique et technologique ou d'un établissement public à
caractère scientifique, culturel et professionnel, lorsque ces
activités font l'objet d'un contrat avec une personne morale de droit
privé ».

3 conditions pour la cession de plein de droit à l'Etat du droit
d'exploitation d'une oeuvre créé par un agent de l'Etat :

1. l'oeuvre est produite dans le cadre de l'exercice de ses fonctions ou d'après les instructions reçues ;
2. cette cession est strictement nécessaire à l'accomplissement d'une mission de service public ;
3. il n'y aura pas d'exploitation commerciale de l'oeuvre (sinon, il n'existe qu'un droit de préférence pour l'Etat).

La dévolution à l'État ne joue pas :

- pour les œuvres créées par des agents qui ne sont pas soumis au
  statut de la fonction publique : par exemple, celles des employés
  d'établissements à caractère industriel ou commercial (droit commun) ;

- pour les œuvres créées par des fonctionnaires dans une activité
  distincte des fonctions résultant de l'emploi statutaire (l'oeuvre
  n'a aucun lien avec la mission de service public et elle en est
  détachable, ou elle n'est pas en concurrence avec celui-ci).

* Droits d'auteur : régime applicable aux enseignants-chercheurs

*Art. L. 111-1 CPI al 4* :

« Les dispositions des articles L. 121-7-1 et L. 131-3-1 à L. 131-3-3
ne s'appliquent pas aux agents auteurs d'œuvres dont la divulgation
n'est soumise, en vertu de leur statut ou des règles qui régissent
leurs fonctions, à aucun contrôle préalable de l'autorité
hiérarchique. »

Cette formule renvoie essentiellement aux professeurs et
universitaires[fn:17].  Il existe une « tolérance traditionnelle »
pour les manuels et traités rédigés par eux dans leur domaine de
compétence[fn:18].

Un EPST ou une université, ne peut donc pas, pour l'accomplissement de
sa mission de service public, bénéficier du mécanisme de cession
automatique des droits d'exploitation sur les œuvres générées par ses
chercheurs ou enseignants-chercheurs participant à des travaux de
recherche (y compris les logiciels).

* Références
** Doctrine

- *Bertrand* (A. R.), « Chapitre 105 -- Auteur et titulaires des droits
  d'auteur » et « Chapitre 202 -- Logiciels », /Droit d'auteur
  2011/2012/, Editions Dalloz, 2010

- *Bensamoun* (A.) et *Groffe* (J.) « Création numérique » [en ligne],
  /Répertoire de droit civil/, Octobre 2013 [actualisé en juin 2014].

- *Dantant* (M.), « Droit d'auteur des chercheurs, Logiciels, Bases de
  Données et Archives Ouvertes » [en ligne], /CNRS / Direction des
  affaires juridiques/, 7 juillet 2014 [consulté le 12 juin 2019],
  disponible à [[http://isidora.cnrs.fr/IMG/pdf/2014-07-07_-_Droit_d_auteur_des_chercheurs_Logiciels_Bases_de_Donne_es_et_Archives_Ouvertes_-_Grenoble_ssc.pdf][cette adresse]].
  
** Textes

- Code de la propriété intellectuelle (version au 12 juin 2019).

- Directive du 14 mai 1991 n°91/250, remplacée par la Directive
  2009/24/CE du Parlement européen et du Conseil du 23 avril 2009
  concernant la protection juridique des programmes d'ordinateur.

- Loi n° 2006-961 du 1 août 2006 relative au droit d'auteur et aux
  droits voisins dans la société de l'information.

* Notes

[fn:1] Directive du 14 mai 1991 (cons. 14) « /les idées et principes qui
       sont à la base de la logique, des algorithmes et des langages de
       programmation ne sont pas protégés en vertu de la présente
       directive /»

[fn:2] CJUE 2 mai 2012, SAS Institute Inc. c/ World Programming Ltd.,
       aff. C-406/10

[fn:3] Civ. 1ère, 13 déc. 2005, n° 03-21.154

[fn:4] Convention de Munich du 5 octobre 1973 sur la délivrance de
       brevets européens (art. 52.2, qui figure à l'article L. 611-10,
       2° CPI)

[fn:5] CJUE 22 déc. 2010, Bezpecnostní softwarová asociace c/ Svaz
       softwarové ochrany, aff. C-393/09, RTD com. 2011. 333, obs.
       Pollaud-Dulian

[fn:6] Cass., ass. plén., 7 mars 1986, Babolat c/ Pachot, n°83-10.477

[fn:7] art. 2.2 de la directive du 14 mai 1991

[fn:8] art. L. 131-4, 5° CPI, sous réserve de art. L. 131-5 CPI (en cas
       de lésion ou de prévision insuffisante des produits de l'œuvre)

[fn:9] art. L. 131-3 CPI

[fn:10] CA Nancy, 1^{er} ch., 13 septembre 1994 : le logiciel créé par
        un salarié grâce au matériel de l'employeur même en dehors de
        ses heures de travail emporte l'application de cette disposition

[fn:11] Art. L. 122-6-1, I, CPI

[fn:12] Art. L. 122-6-1, II CPI

[fn:13] Art. L. 122-6-1, III CPI

[fn:14] Art. L. 122-6-1, IV CPI

[fn:15] Art. L. 121-3, al. 3 CPI

[fn:16] [[https://www.impots.gouv.fr][www.impots.gouv.fr]]

[fn:17] André R. Bertrand, « Chapitre 105 -- Auteur et titulaires des
        droits d'auteur », 2010

[fn:18] C. Bernault, « Le droit d'auteur des enseignants :
        l'enseignant est-il un fonctionnaire « comme les autres » ? »,
        /CCE/ mars 2010 n^{o} 3 p. 7 § 6. Lorsque l'enseignant est lié à
        établissement privé le droit commun s'applique, et la cession
        des droits à l'employeur doit pour être valide se conformer au
        formalisme de l'article L. 131-3 du CPI (Crim. 22 sept. 2009,
        n^{o} 09-81.014  , /CCE/ févr. 2010 n^{o} 2 p. 34 § 13 note Caron).
